<testsuites name="results">
  <testsuite name="all" package="all">
    <property name="random_seed" value="1716036825" />
    <testcase name="run_test_write_001" classname="test_axi_pim" file="/home/jueun/.local/lib/python3.10/site-packages/cocotb/regression.py" lineno="731" time="4.051050901412964" sim_time_ns="1000000000" ratio_time="246849527.27975118">
      <failure message="Test failed with RANDOM_SEED=1716036825" />
    </testcase>
    <testcase name="run_test_write_002" classname="test_axi_pim" file="/home/jueun/.local/lib/python3.10/site-packages/cocotb/regression.py" lineno="731" time="8.273124694824219e-05" sim_time_ns="1000000000" ratio_time="12087331412103.746">
      <failure message="Test failed with RANDOM_SEED=1716036825" />
    </testcase>
    <testcase name="run_test_write_003" classname="test_axi_pim" file="/home/jueun/.local/lib/python3.10/site-packages/cocotb/regression.py" lineno="731" time="5.5789947509765625e-05" sim_time_ns="1000000000" ratio_time="17924376068376.07">
      <failure message="Test failed with RANDOM_SEED=1716036825" />
    </testcase>
    <testcase name="run_test_write_004" classname="test_axi_pim" file="/home/jueun/.local/lib/python3.10/site-packages/cocotb/regression.py" lineno="731" time="5.459785461425781e-05" sim_time_ns="1000000000" ratio_time="18315737991266.375">
      <failure message="Test failed with RANDOM_SEED=1716036825" />
    </testcase>
    <testcase name="run_test_read_001" classname="test_axi_pim" file="/home/jueun/.local/lib/python3.10/site-packages/cocotb/regression.py" lineno="731" time="5.507469177246094e-05" sim_time_ns="1000000000" ratio_time="18157160173160.17">
      <failure message="Test failed with RANDOM_SEED=1716036825" />
    </testcase>
    <testcase name="run_test_read_002" classname="test_axi_pim" file="/home/jueun/.local/lib/python3.10/site-packages/cocotb/regression.py" lineno="731" time="5.4836273193359375e-05" sim_time_ns="1000000000" ratio_time="18236104347826.086">
      <failure message="Test failed with RANDOM_SEED=1716036825" />
    </testcase>
    <testcase name="run_test_read_003" classname="test_axi_pim" file="/home/jueun/.local/lib/python3.10/site-packages/cocotb/regression.py" lineno="731" time="5.435943603515625e-05" sim_time_ns="1000000000" ratio_time="18396070175438.598">
      <failure message="Test failed with RANDOM_SEED=1716036825" />
    </testcase>
    <testcase name="run_test_read_004" classname="test_axi_pim" file="/home/jueun/.local/lib/python3.10/site-packages/cocotb/regression.py" lineno="731" time="5.459785461425781e-05" sim_time_ns="1000000000" ratio_time="18315737991266.375">
      <failure message="Test failed with RANDOM_SEED=1716036825" />
    </testcase>
    <testcase name="run_pim_test_001" classname="test_axi_pim" file="/home/jueun/.local/lib/python3.10/site-packages/cocotb/regression.py" lineno="731" time="5.412101745605469e-05" sim_time_ns="1000000000" ratio_time="18477110132158.59">
      <failure message="Test failed with RANDOM_SEED=1716036825" />
    </testcase>
  </testsuite>
</testsuites>
